import Link from 'next/link'
import { Headphones, Mail, MessageCircle, Phone } from 'lucide-react'

const faqs = [
  ['Order kaise track karun?', 'Account → My Orders mein order kholkar confirmed, packed, shipped aur delivered timeline dekhein.'],
  ['COD available hai?', 'Haan, zyada serviceable pincodes par COD available hai. Checkout mein pincode dalte hi availability check hoti hai.'],
  ['Coupon kaise apply hota hai?', 'Checkout summary mein coupon code enter karein. Discount server par validate hokar total mein dikhega.'],
  ['Return kaise request karun?', 'Delivered order detail page par “Request a return / refund” kholein, product aur reason select karke submit karein.'],
  ['Invoice kahan milega?', 'Har order detail page par Invoice PDF link available hai.'],
  ['Bulk quantity chahiye?', 'Bulk Orders form bhejein. B2B team volume price aur delivery plan ke saath contact karegi.'],
]
export default function HelpPage() { return <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-10 sm:px-6"><div className="text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-sage text-brand"><Headphones /></span><h1 className="mt-4 font-display text-4xl font-extrabold text-ink">How can we help?</h1><p className="mt-2 text-sm text-body">Order, delivery, payment ya product—seedha jawab yahan milega.</p></div><section className="mx-auto mt-9 max-w-3xl space-y-3">{faqs.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-line bg-card p-5 shadow-card"><summary className="cursor-pointer list-none font-bold text-ink">{question}<span className="float-right text-brand group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-6 text-body">{answer}</p></details>)}</section><section className="mt-10 grid gap-4 sm:grid-cols-3"><Contact icon={MessageCircle} title="WhatsApp chat" text="Fast support" href="https://wa.me/919876543210?text=Namaste%20KisanMart" /><Contact icon={Phone} title="Call us" text="+91 98765 43210" href="tel:+919876543210" /><Contact icon={Mail} title="Email" text="support@kisanmart.in" href="mailto:support@kisanmart.in" /></section><p className="mt-8 text-center text-sm text-muted">B2B requirement? <Link href="/bulk-orders" className="font-bold text-brand">Request a bulk quote</Link></p></main> }
function Contact({ icon: Icon, title, text, href }: { icon: typeof Phone; title: string; text: string; href: string }) { return <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="rounded-2xl border border-line bg-card p-5 text-center shadow-card"><Icon className="mx-auto text-brand" /><h2 className="mt-3 font-bold text-ink">{title}</h2><p className="mt-1 text-xs text-muted">{text}</p></a> }
