'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Droplets, ShieldCheck, Sprout } from 'lucide-react'

const crops = {
  wheat: { name: 'Wheat / गेहूँ', season: 'Rabi · Oct–Apr', tips: ['Certified seed ko recommended depth par sow karein.', 'Soil test ke basis par NPK schedule banayein.', 'Rust aur aphid ke early signs weekly check karein.'], products: [{ label: 'Wheat seeds', q: 'wheat' }, { label: 'Crop nutrition', q: 'fertilizer' }, { label: 'Sprayers', q: 'sprayer' }] },
  rice: { name: 'Rice / धान', season: 'Kharif · Jun–Nov', tips: ['Nursery seed treatment se early disease risk kam hota hai.', 'Field ko continuously flood rakhna hamesha zaroori nahi—AWD consider karein.', 'Stem borer aur leaf folder scouting karein.'], products: [{ label: 'Paddy seeds', q: 'paddy' }, { label: 'Bio-fertilizers', q: 'bio' }, { label: 'Crop protection', q: 'insecticide' }] },
  cotton: { name: 'Cotton / कपास', season: 'Kharif · Apr–Jan', tips: ['Local recommendation ke hisaab se variety choose karein.', 'Whitefly aur pink bollworm traps ka regular observation karein.', 'Excess nitrogen se sucking pests badh sakte hain.'], products: [{ label: 'Cotton seeds', q: 'cotton' }, { label: 'Pheromone traps', q: 'trap' }, { label: 'Micronutrients', q: 'nutrient' }] },
  tomato: { name: 'Tomato / टमाटर', season: 'Multiple seasons', tips: ['Healthy, disease-free seedlings use karein.', 'Drip irrigation se foliage dry aur water use efficient rahta hai.', 'Blight symptoms par affected leaves isolate karein.'], products: [{ label: 'Vegetable seeds', q: 'tomato' }, { label: 'Drip supplies', q: 'drip' }, { label: 'Fungicides', q: 'fungicide' }] },
  mustard: { name: 'Mustard / सरसों', season: 'Rabi · Sep–Mar', tips: ['Timely sowing aphid pressure ko reduce kar sakti hai.', 'Sulphur requirement soil test ke saath plan karein.', 'Flowering stage par irrigation timing carefully manage karein.'], products: [{ label: 'Mustard seeds', q: 'mustard' }, { label: 'Sulphur nutrition', q: 'sulphur' }, { label: 'Protection', q: 'pesticide' }] },
} as const

export default function CropAdvisor() {
  const [selected, setSelected] = useState<keyof typeof crops>('wheat')
  const crop = crops[selected]
  return <div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="rounded-2xl border border-line bg-card p-4 shadow-card"><label className="text-xs font-bold uppercase tracking-wider text-muted">Select your crop</label><div className="mt-3 space-y-2">{Object.entries(crops).map(([key, value]) => <button type="button" key={key} onClick={() => setSelected(key as keyof typeof crops)} className={`w-full rounded-xl px-4 py-3 text-left text-sm font-bold transition ${selected === key ? 'bg-brand text-white' : 'bg-surface text-ink hover:bg-sage'}`}>{value.name}</button>)}</div></aside><section className="rounded-3xl border border-brand/15 bg-brand/5 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-brand">{crop.season}</p><h2 className="mt-2 font-display text-3xl font-extrabold text-ink">{crop.name} guide</h2></div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand text-white"><Sprout /></span></div><div className="mt-6 space-y-3">{crop.tips.map((tip, index) => <div key={tip} className="flex gap-3 rounded-xl bg-white/80 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-sage text-xs font-bold text-brand">{index + 1}</span><p className="text-sm leading-6 text-body">{tip}</p></div>)}</div><h3 className="mt-7 flex items-center gap-2 font-bold text-ink"><ShieldCheck size={18} className="text-brand" /> Useful product groups</h3><div className="mt-3 flex flex-wrap gap-2">{crop.products.map((product) => <Link key={product.q} href={`/products?q=${encodeURIComponent(product.q)}`} className="flex items-center gap-1.5 rounded-full border border-brand/20 bg-white px-4 py-2 text-sm font-bold text-brand">{product.label} <ArrowRight size={14} /></Link>)}</div><p className="mt-7 flex items-start gap-2 text-xs leading-5 text-muted"><Droplets size={16} className="mt-0.5 shrink-0" /> General guidance only. Exact dose, product label aur local Krishi Vigyan Kendra/agronomist advice follow karein.</p></section></div>
}
