import { RotateCcw } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { updateReturnStatus } from '@/app/admin/actions'

const STATUSES = ['requested', 'approved', 'rejected', 'picked_up', 'refunded']

export default async function AdminReturnsPage() {
  const supabase = await createClient()
  const { data } = await supabase.from('return_requests')
    .select('*, orders(shipping_name, shipping_phone, total_amount), order_items(product_name)')
    .order('created_at', { ascending: false })
  return <main className="w-full p-5 sm:p-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">After-sales</p><h1 className="mt-2 text-3xl font-extrabold text-ink">Returns & refunds</h1><p className="mt-1 text-sm text-body">{data?.length ?? 0} requests</p><div className="mt-7 overflow-x-auto rounded-2xl border border-line bg-white shadow-card"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-line bg-sage text-xs uppercase tracking-wider text-brand-dark/60"><tr><th className="px-5 py-4">Request</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Reason</th><th className="px-5 py-4">Refund</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-line">{(data ?? []).map((request) => <tr key={request.id} className="align-top"><td className="px-5 py-4"><p className="font-mono text-xs font-bold text-ink">#{request.order_id.slice(0, 8).toUpperCase()}</p><p className="mt-1 text-xs text-muted">{request.order_items?.product_name ?? 'Entire order'}</p><span className="mt-2 inline-flex rounded-full bg-sage px-2 py-1 text-[10px] font-bold uppercase text-brand-dark">{request.status.replace('_', ' ')}</span></td><td className="px-5 py-4"><p className="font-bold text-ink">{request.orders?.shipping_name}</p><p className="text-xs text-muted">{request.orders?.shipping_phone}</p></td><td className="max-w-sm px-5 py-4"><p className="font-semibold text-ink">{request.reason}</p><p className="mt-1 text-xs text-body">{request.details || 'No extra details'}</p></td><td className="px-5 py-4 font-bold text-ink">{request.refund_amount == null ? '—' : `₹${Number(request.refund_amount).toLocaleString('en-IN')}`}</td><td className="px-5 py-4"><form action={updateReturnStatus} className="flex items-center gap-2"><input type="hidden" name="request_id" value={request.id} /><select name="status" defaultValue={request.status} className="rounded-lg border border-line px-2.5 py-2 text-xs">{STATUSES.map((status) => <option key={status}>{status}</option>)}</select><input name="refund_amount" type="number" min="0" step="0.01" placeholder="Refund ₹" defaultValue={request.refund_amount ?? ''} className="w-24 rounded-lg border border-line px-2.5 py-2 text-xs" /><button className="rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white">Save</button></form></td></tr>)}{!data?.length && <tr><td colSpan={5} className="py-16 text-center text-muted"><RotateCcw className="mx-auto" /><p className="mt-2">No return requests</p></td></tr>}</tbody></table></div></main>
}
