import { MessageSquareQuote } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { updateQuoteStatus } from '@/app/admin/actions'

const statuses = ['new', 'contacted', 'quoted', 'closed']
export default async function AdminQuotesPage() {
  const supabase = await createClient()
  const { data } = await supabase.from('bulk_quote_requests').select('*').order('created_at', { ascending: false })
  return <main className="w-full p-5 sm:p-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">B2B sales</p><h1 className="mt-2 text-3xl font-extrabold text-ink">Bulk quote requests</h1><p className="mt-1 text-sm text-body">{data?.length ?? 0} enquiries</p><div className="mt-7 grid gap-4 xl:grid-cols-2">{(data ?? []).map((quote) => <article key={quote.id} className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex justify-between gap-4"><div><h2 className="font-bold text-ink">{quote.name}{quote.organisation ? ` · ${quote.organisation}` : ''}</h2><p className="mt-1 text-xs text-muted">{quote.phone}{quote.email ? ` · ${quote.email}` : ''}</p></div><span className="h-fit rounded-full bg-sage px-2.5 py-1 text-[10px] font-bold uppercase text-brand-dark">{quote.status}</span></div><div className="mt-4 grid gap-3 rounded-xl bg-surface p-4 text-sm sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-muted">Products</p><p className="mt-1 text-body">{quote.products_needed}</p></div><div><p className="text-xs font-bold uppercase text-muted">Quantity / place</p><p className="mt-1 text-body">{quote.quantity_note} · {quote.delivery_place}</p></div></div>{quote.message && <p className="mt-3 text-sm text-body">{quote.message}</p>}<form action={updateQuoteStatus} className="mt-4 flex gap-2"><input type="hidden" name="quote_id" value={quote.id} /><select name="status" defaultValue={quote.status} className="rounded-lg border border-line px-3 py-2 text-xs">{statuses.map((status) => <option key={status}>{status}</option>)}</select><button className="rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white">Update</button></form></article>)}{!data?.length && <div className="rounded-2xl border border-dashed border-line py-16 text-center text-muted"><MessageSquareQuote className="mx-auto" /><p className="mt-2">No quote requests</p></div>}</div></main>
}
